variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - test
  - build
  - report

# Кэширование Maven зависимостей
.maven_cache: &maven_cache
  cache:
    key: ${CI_COMMIT_REF_SLUG}-maven
    paths:
      - .m2/repository

test:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  services:
    - name: docker:24-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  <<: *maven_cache
  script:
    - mvn clean package -DskipTests -B
    - export APP_JAR="$(ls target/*.jar | grep -v '\.original\.jar' | head -n 1)"
    - echo "Using JAR - $APP_JAR"
    - apt-get update && apt-get install -y curl
    - java -jar "$APP_JAR" --spring.profiles.active=test &
    - until curl -sS http://localhost:8081 > /dev/null 2>&1; do echo "waiting for app on 8081..."; sleep 5; done
    - mvn verify -B
  artifacts:
    when: always
    paths:
      - target/allure-results/
      - target/surefire-reports/
      - target/failsafe-reports/
    reports:
      junit: target/surefire-reports/TEST-*.xml

build-docker:
  stage: build
  needs: [test]
  image: docker:24
  services:
    - name: docker:24-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - >
      if [ -n "$CI_REGISTRY_IMAGE" ]; then
        IMAGE_NAME="$CI_REGISTRY_IMAGE";
      else
        IMAGE_NAME="$CI_PROJECT_NAME";
      fi;
      echo "Using image name: ${IMAGE_NAME}";
      docker build -t "${IMAGE_NAME}:${CI_COMMIT_SHA}" -t "${IMAGE_NAME}:latest" .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

allure-report:
  stage: report
  needs:
    - job: test
      artifacts: true
      optional: true
  when: always 
  image: frankescobar/allure-docker-service
  script:
    - allure generate target/allure-results --clean -o public
    - echo "${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_REF_SLUG}/download?job=allure-report"
    - echo "Скачай архив → распакуй → открой в браузере файл public/index.html"
  artifacts:
    when: always
    paths:
      - public
